// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSj58pEIjlpKqik71IVlz8xSVmQ9ny82k',
    appId: '1:347106065165:web:adffa96cd4b03eba710e44',
    messagingSenderId: '347106065165',
    projectId: 'playoffs-score-card',
    authDomain: 'playoffs-score-card.firebaseapp.com',
    databaseURL: 'https://playoffs-score-card-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'playoffs-score-card.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc4m-nPgzGF4fLZf8DKfa8JUlaXL4F0-Y',
    appId: '1:347106065165:android:b0b5510335ce1a61710e44',
    messagingSenderId: '347106065165',
    projectId: 'playoffs-score-card',
    databaseURL: 'https://playoffs-score-card-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'playoffs-score-card.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtwR1Po85NVjmVnaTVlSthxcYMxn4AM8Q',
    appId: '1:347106065165:ios:e539c06f6dd45a13710e44',
    messagingSenderId: '347106065165',
    projectId: 'playoffs-score-card',
    databaseURL: 'https://playoffs-score-card-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'playoffs-score-card.appspot.com',
    iosClientId: '347106065165-b28j61u8q8iu3uevl4f46hb5jnpda3jo.apps.googleusercontent.com',
    iosBundleId: 'com.playoffsScoreCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtwR1Po85NVjmVnaTVlSthxcYMxn4AM8Q',
    appId: '1:347106065165:ios:e539c06f6dd45a13710e44',
    messagingSenderId: '347106065165',
    projectId: 'playoffs-score-card',
    databaseURL: 'https://playoffs-score-card-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'playoffs-score-card.appspot.com',
    iosClientId: '347106065165-b28j61u8q8iu3uevl4f46hb5jnpda3jo.apps.googleusercontent.com',
    iosBundleId: 'com.playoffsScoreCard',
  );
}
